### ISSUE TITLE
Feature: User can create an account and login

### ISSUE THREAD

**Issue by marissalortega** [marissalortega/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account and login to the app.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User is prompted to login, but if they do not already have account, they can register for one.  They will be prompted to use an uppercase letter, number and special character when creating their account.  Upon account creation, the user is redirected back to the login page where they can enter their credentials and login.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90414477/196326974-bdd7b797-9ee7-4b58-91d1-a1955b32830a.png)
![image](https://user-images.githubusercontent.com/90414477/196327001-8ce4a8cc-7b31-4afc-b983-cfe04c9fd804.png)
![image](https://user-images.githubusercontent.com/90414477/196327114-93b9ebe2-b5bc-4489-b34b-0bced8e0f24a.png)
![image](https://user-images.githubusercontent.com/90414477/196327138-bddff1c0-b573-4caf-9bb1-0e422e1d56ea.png)
![image](https://user-images.githubusercontent.com/90414477/196327152-bfc0eb03-c8ae-4de4-be37-8f719e67d451.png)
![image](https://user-images.githubusercontent.com/90414477/196327169-e1cc3351-a829-4d8b-81bf-b67593f34d0c.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to create tables in database.

### ☁️ Server Tasks

- [x] Update `server/index.js` to `POST` a new username and password to the `"users"` table.
- [x] Update `server/index.js` to hash the password and store it in the `"users"` table.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to display a `navbar`.
- [x] Create a component for the `login` fields.
- [x] Create a component for the `register` fields.
- [x] Create a component for the page container.
- [x] Create a `redirect.jsx` file for hashed routing.
- [x] CSS for the login page.
- [x] CSS for the register page.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
