### ISSUE TITLE
Feature: User can add client info (name, address, phone number, etc.)

### ISSUE THREAD

**Issue by marissalortega** [marissalortega/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add their client's information to a contact form and display the user in the contacts page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User has access to a client list that displays a list of saved clients.  When the user clicks on the client name it takes them to the client info - name, email, phone number, address, and birthday.  If they need to add a new client, they select that from the client list.  

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90414477/199381930-415a618d-e2c5-461d-bde9-18de639c2b8e.png)
![image](https://user-images.githubusercontent.com/90414477/199381992-9ff8a77e-1318-412b-99ba-cbd46aaf7d03.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to `POST` a new client to the "users" table. Name, email, address, phone number, birthday.
- [x] Update `server/index.js` to `GET` client info and display it on the client card.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update redirect to match the styling of the rest of the app.
- [x] Create a component for new client form.
- [ ] Create component to display client info.
- [ ] Create component to display client list.

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
